### ISSUE TITLE
The compiled release contains a virus.

### ISSUE THREAD

**Issue by builderdev212** [robiot/AlphaClicker#24]
Release 1.3 contains a trojan virus in the .exe. Please do NOT download and install this on your computer.
https://www.virustotal.com/gui/file/84f3e2049740ebbcfb5fe827cc6068c6f8691bcaefa781a9f2af7a07d944443b/detection

**Comment by ryanlua** [comment]
Could be a false negative. Not saying it's completely safe but just because one vendor detects it as a Trojan doesn't mean it has to be dangerous. 

Remember to compile it yourself if you want to be extra secure since it's open source after all.

**Comment by robiot** [comment]
This is a false claim, as you can "decompile" the .exe and look through the distributed source code of program with something like ILSpy, and check yourself if it contains unwanted code. I am certain I did not include that in the .exe, but you are free to check yourself.

Virustotal gives false positives since this program integrates with Windows APIs to simulate clicks.
